baseURL = "https://borong.bangunan.co/"
languageCode = "id"
title = "Borong Bangunan | Kontraktor Borong Bangunan Rumah, Kantor, Ruko Berpengalaman"
theme = "saeseen-hugo"
summaryLength = 25
paginate = 6

[permalinks]
  post = "/:slug/"
  page = "/:slug/"
  category = "/:slug/"

[params]
  # Site-wide settings
  meta_description = "Tukang Borong Bangunan - Kami melayani pembangunan rumah, kantor, dan ruko dengan sistem borongan dengan hasil berkualitas dan tepat waktu"
  viewport = "width=device-width, initial-scale=1.0"
  fontawesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
  logo = "/images/logo/bangunanco-logo-web.png"
  logo_amp = "/images/logo/bangunanco-512x512.png"
  footer_logo = "/images/logo/bangunanco-logo-putih.png"
  favicon = "/images/logo/bangunanco-512x512.png"
  featured_image = "/images/admin/featured-image.png"
  author = "K. Yaman"
  telepon = "//+6285776786091"
  whatsapp = "//api.whatsapp.com/send?phone=6285776786091&text=*Halo bangunan.co*%20%3A"
  enableWhatApps = true
  enableTelepon = true
  tocMinWordCount = 300
  tableOfContent = "Daftar Isi:"
  geo_latitude = -6.595038
  geo_longitude = 106.817787
  opening_hours = "Mo-Sa 08:00-17:00"

  # Schema settings
  keywords = ["jasa borong bangunan", "kontraktor berpengalaman", "bangun rumah borongan", "borong bangunan ruko", "borong bangunan kantor", "jasa bangun rumah murah"]
  base_price = 3000000
  price_range = 3000000
  free_consultation = true
  service_types = [
  "Borong Pembangunan Rumah",
  "Borong Pembangunan Kantor",
  "Borong Pembangunan Ruko",
  "Renovasi Rumah",
  "Renovasi Kantor",
  "Renovasi Ruko"
  ]
  categories = ["Jasa Kontraktor", "Borongan Bangunan", "Pembangunan Rumah", "Renovasi Bangunan"]
  payment_methods = ["Bayar Bertahap", "Transfer Bank", "Bayar DP 30%", "Transfer Setelah Proyek Selesai"]
  cancellation_policies = [
  "Layanan dapat dibatalkan jika tidak sesuai dengan kesepakatan awal.",
  "Pengembalian biaya jika hasil tidak sesuai standar yang disepakati.",
  "Revisi atau perbaikan gratis jika hasil tidak memuaskan."
  ]
  area_served = ["Jakarta", "Bogor", "Depok", "Tangerang", "Bekasi", "Cikarang", "Karawang", "Subang", "Cikampek", "Purwakarta", "Rangkas Bitung", "Serang"]
  service_output = "Bangunan berkualitas dengan sistem borongan, sesuai spesifikasi dan tepat waktu."

 # Hero Section
  hero_image = "/images/admin/bg_bangunanco.png"
  hero_title = "Kontraktor Borong Bangunan Berpengalaman"
  hero_description = "Kami menyediakan jasa borong bangunan rumah, kantor, dan ruko dengan pengalaman bertahun-tahun. Solusi terbaik untuk setiap proyek konstruksi Anda, dengan tenaga ahli dan material berkualitas."
  hero_cta_text = "Selengkapnya"
  services_cta_text = "Cek Harga Borongan"

  # Footer Section
  footer_about_title = "Keunggulan Kami"
  footer_about_description = "Jangkauan luas, bebas biaya survey, tanpa biaya tersembunyi, tukang berpengalaman, sistem pembayaran aman, buka setiap hari, gratis konsultasi, dan material lengkap untuk semua proyek konstruksi."
  footer_services_title = "Kenapa Pilih Kami"
  footer_contact_title = "Kontak Kami"
  footer_bottom_text = "@2024 Bangunan.co. Semua Hak Dilindungi."

  # Testimonials Section
  testimonials_title = "Apa Kata Klien Kami"

  [[params.footer_services]]
  text = "Borong.bangunan.co menawarkan layanan kontraktor borongan berkualitas untuk rumah, kantor, dan ruko. Kami mengutamakan kualitas kerja dan kepuasan pelanggan dengan tenaga ahli, material terbaik, dan harga yang bersaing. Pilih kami untuk hasil proyek yang memuaskan dan tepat waktu."

  [[params.footer_contact]]
    icon = "fas fa-map-marker-alt"
    text = "Jalan Lkr. Dramaga No. 09, Bogor - JaBar"
  [[params.footer_contact]]
    icon = "fas fa-phone-alt"
    text = "+62 857-7678-6091"
  [[params.footer_contact]]
    icon = "fas fa-envelope"
    text = "bangunanco@gmail.com"

[[params.testimonials]]
  avatar = "/images/admin/avatar1.png"
  name = "{Budi|Joko|Andi|Eko|Rudi|Agus|Wawan|Fajar|Rio|Toni}"
  message = "{Saya menggunakan jasa borong.bangunan.co untuk {renovasi|pembaruan} rumah saya, dan hasilnya {sangat memuaskan|luar biasa}. Proyek selesai {tepat waktu|sesuai jadwal} dan {kualitas|mutu} pekerjaannya {luar biasa|sangat baik}.|Jasa borong.bangunan.co {memenuhi harapan|sangat membantu} dalam renovasi rumah saya. Pekerjaan selesai tepat waktu dan hasilnya memuaskan.}"
  response = "{Terima kasih atas kepercayaannya! Kami senang dapat memberikan {hasil yang memuaskan|kualitas terbaik} untuk renovasi rumah Anda.|Kami sangat menghargai kepercayaan Anda. Senang Anda puas dengan hasilnya!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar2.png"
  name = "{Siti|Rina|Dewi|Ayu|Sari|Fitri|Lina|Diah|Maya|Nur}"
  message = "{Tim borong.bangunan.co {sangat profesional|berpengalaman} dalam {membangun|mengembangkan} ruko saya. Proses pengerjaan {lancar|efisien} dan hasil akhirnya {sesuai dengan yang saya harapkan|memuaskan}.|Borong.bangunan.co memberikan layanan {profesional|terbaik} dalam pembangunan ruko saya, dengan hasil akhir yang {luar biasa|hebat}.}"
  response = "{Kami sangat menghargai ulasannya. Senang mendengar bahwa Anda puas dengan {pembangunan|konstruksi} ruko kami.|Terima kasih atas kepercayaan Anda. Kami senang bisa memberikan hasil terbaik untuk proyek ruko Anda.}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar3.png"
  name = "{Joko|Agus|Bayu|Galih|Rizal|Bambang|Faisal|Ali|Toni|Deni}"
  message = "{Pengerjaan kantor saya oleh borong.bangunan.co {sangat rapi|bersih} dan {berkualitas|berstandar tinggi}. Layanan mereka {sangat cepat|efisien} dan {tanggap|responsif} terhadap kebutuhan saya.|Kantor saya dikerjakan oleh tim borong.bangunan.co dengan {kualitas yang baik|hasil memuaskan}. Timnya cepat tanggap dan bekerja dengan rapi.}"
  response = "{Terima kasih! Kami berkomitmen memberikan {hasil terbaik|kualitas maksimal} untuk proyek kantor Anda.|Kami senang dapat mendukung proyek Anda dengan layanan berkualitas. Terima kasih atas kepercayaannya!}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar4.png"
  name = "{Andi|Eko|Deni|Hendra|Toni|Wawan|Gilang|Ari|Benny|Yudi}"
  message = "{Saya {sangat puas|senang} dengan hasil borongan bangunan rumah saya. Hasilnya {sesuai dengan desain yang diinginkan|memenuhi ekspektasi} dan prosesnya {sangat efisien|cepat}.|Layanan borongan bangunan dari borong.bangunan.co {sangat memuaskan|memenuhi harapan}, dengan hasil yang {luar biasa|hebat} sesuai desain yang diinginkan.}"
  response = "{Senang mendengar rumah Anda sesuai dengan harapan. Terima kasih atas kepercayaannya dalam menggunakan layanan kami!|Kami sangat menghargai kepercayaan Anda. Terima kasih telah mempercayakan proyek rumah Anda kepada kami!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar5.png"
  name = "{Rina|Siti|Lina|Dewi|Ayu|Sari|Fitri|Maya|Nur|Diah}"
  message = "{Pelayanan yang diberikan oleh borong.bangunan.co {sangat memuaskan|hebat}. Mereka memberikan {solusi yang tepat|saran yang baik} untuk proyek bangunan kantor saya.|Layanan dari borong.bangunan.co {memenuhi kebutuhan|sangat membantu} proyek bangunan kantor saya, dengan solusi yang {efektif|bermanfaat}.}"
  response = "{Terima kasih! Kami senang dapat membantu mewujudkan proyek bangunan kantor Anda dengan solusi {terbaik|tepat}.|Kami sangat menghargai ulasan Anda. Terima kasih telah memilih layanan kami!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar6.png"
  name = "{Eko|Rio|Galih|Faisal|Yanto|Benny|Toni|Deni|Rizal|Wawan}"
  message = "{Proyek renovasi interior rumah saya berjalan {lancar|dengan baik} berkat borong.bangunan.co. Hasilnya {sangat elegan|luar biasa} dan sesuai dengan {keinginan|ekspektasi} saya.|Renovasi interior rumah saya dibantu oleh borong.bangunan.co dengan hasil yang {elegan|hebat} dan prosesnya {efisien|lancar}.}"
  response = "{Kami senang mendengar bahwa renovasi interior rumah Anda memuaskan. Terima kasih atas {ulasannya|kepercayaannya}!|Terima kasih telah memilih layanan kami untuk renovasi rumah Anda. Kami senang bisa memenuhi ekspektasi Anda.}"
  rating = 4

[[params.tabelItems]]
  name = "Borong Pembangunan Rumah"
  price = "3.000.000 /m"
[[params.tabelItems]]
  name = "Borong Pembangunan Kantor"
  price = "4.500.000 /m"
[[params.tabelItems]]
  name = "Borong Pembangunan Ruko"
  price = "4.000.000 /m"
[[params.tabelItems]]
  name = "Renovasi Rumah"
  price = "3.500.000 /m"
[[params.tabelItems]]
  name = "Renovasi Kantor"
  price = "6.000.000 /m"

[params.appliList]
  "Borong Pembangunan Rumah" = "pembangunan rumah dari nol, renovasi besar"
  "Borong Pembangunan Kantor" = "pembangunan kantor skala kecil hingga menengah"
  "Borong Pembangunan Ruko" = "pembangunan ruko untuk usaha atau tempat tinggal"
  "Renovasi Rumah" = "perbaikan, peningkatan, dan renovasi rumah"
  "Renovasi Kantor" = "renovasi ruang kantor untuk penataan ulang atau ekspansi"

[params.kegunaanList]
  "Borong Pembangunan Rumah" = "membangun rumah baru dengan hasil yang berkualitas dan cepat"
  "Borong Pembangunan Kantor" = "membangun kantor dengan desain yang fungsional dan modern"
  "Borong Pembangunan Ruko" = "pembangunan ruko dengan konsep multi-fungsi, untuk bisnis dan tempat tinggal"
  "Renovasi Rumah" = "meningkatkan estetika dan fungsi rumah melalui renovasi menyeluruh"
  "Renovasi Kantor" = "membuat kantor lebih nyaman dan produktif dengan renovasi yang tepat"

  # Menu Section
  [[params.menu_items]]
    title = "Beranda"
    url = "/"
  [[params.menu_items]]
    title = "Profile"
    url = "https://bangunan.co/profile/"
  [[params.menu_items]]
    title = "Daftar Harga"
    url = "https://bangunan.co/daftar-harga/"

[params.header]
   title = "Kontraktor Borongan Rumah, Kantor, Ruko | "
   highlight = "Bangunan.co"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 100

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "AMP"]

[outputFormats]
  [outputFormats.AMP]
    mediaType = "text/html"
    baseName = "amp/index"
    path = ""
    isPlainText = false
    permalinkable = true
    rel = "amphtml"